#!/bin/bash
#
# Checks whether on AC or battery power at boot and
# switches to psave performance or powersaving mode as appropriate
#


. /etc/rc.conf
. /etc/rc.d/functions
. /usr/bin/psave_functions


DAEMON_NAME=psaved


case "$1" in
  
  start)
        stat_busy "Starting $DAEMON_NAME"
        if [ ! -f /var/run/daemons/$DAEMON_NAME ]; then
        
          current_pow_status
          case $? in
                              
                  1) /usr/bin/psave false ;;
                              
                  0) /usr/bin/psave true ;;
                              
          esac
          
          if [ $? -gt 0 ]; then
            stat_fail
            exit 1
          else
            add_daemon $DAEMON_NAME
            stat_done
          fi
        else
          stat_fail
          exit 1
        fi
        ;;  
          
   stop) 
        stat_busy "Stopping $DAEMON_NAME"
        [ -f /var/run/daemons/$DAEMON_NAME ]
        if [ $? = 0 ]; then
          rm_daemon $DAEMON_NAME
          stat_done
        else
          stat_fail
          exit 1
        fi
        ;;
        
restart)
        $0 stop
        sleep 1
        $0 start
        ;;
        
      *)
        echo "usage: $0 {start|stop|restart}"
        ;;  
esac



